### ISSUE TITLE
ML2 TA feedback

### ISSUE THREAD

**Issue by afshinamini** [UBC-MDS/DSCI532_Group17#22]
Hi Folks,

Good job with the dashboard!
Few comments:
- make the fonts for bar charts larger.
- Add more color to your dashboard.
- Maybe a slider to filter "Overall"? 
- Also it would be useful for reader to see some explanation/definition for parameters such as Overall or Potential.

Cheers,
Afshin

**Comment by mmyz88** [comment]
Thank you @afshinamini ! I agree with your suggestions. We will note them down and implement them next week.
