### ISSUE TITLE
Could you use this optimized version of your gif?

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI532_Group17#38]
Hey @mmyz88 @GuanshuTao @sunsiche @yuanxiongbear   ! Would you mind using this optimized version of your gif? The dashboard is having some performance issues and I am thinking it might be related to all the gifs. It is still pretty good quality and 3 MB instead of 12 MB. Sorry for the trouble!

![ezgif com-optimize (4)](https://user-images.githubusercontent.com/4560057/107171331-5e5b5280-6977-11eb-9f64-e975a5c07521.gif)

**Comment by mmyz88** [comment]
Hey @joelostblom no problem! The repo is now updated with the 3MB gif

**Comment by joelostblom** [comment]
Perfect thank you!
